### ISSUE TITLE
Unexpected values in POST arguments to interpret.php should be ignored

### ISSUE THREAD

**Issue by AdamTReineke** [twodee/madeup#2]
(Redacted)

**Comment by twodee** [comment]
@AdamTReineke redacted his message to give me time to fix the issue. Here's his original message:

> `extension` expects `json` and `obj`
> `mode` expects `PATH`, `SURFACE`, (others?)
> `shadingMode` expects `SMOOTH`,`FLAT`, (others?)

> If an unknown value is provided, the script should exit or pick a default value. This would prevent potentially dangerous values from being passed in. (Example, a POST request with an extension value of `obj/../../../../../etc/motd` will output the contents of that file in the `model` property of the response JSON. A less innocent file could be printed the same way.)

**Comment by twodee** [comment]
Fixed by 1a03b0ea466ff2cfe9990966b500a0e9a966bffc.

I've been letting the the interpreter itself catch invalid geometry and shading enums, as it knows better what it supports. The extension issue was a definite issue, though it would have overwritten rather than read a file.

Thanks!

**Comment by AdamTReineke** [comment]
(It wouldn't have overwritten unwritable files that are still readable, like /etc/motd.)

**Comment by twodee** [comment]
Ahh, I see your point now. If the write fails, it will still try to read the protected output file and send it back to the client.
